CREATE TABLE kline_data
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symbol                       VARCHAR(255)                            NOT NULL,
    open_time                    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    close_time                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    interval                     VARCHAR(255)                            NOT NULL,
    open                         DECIMAL(20, 8)                          NOT NULL,
    high                         DECIMAL(20, 8)                          NOT NULL,
    low                          DECIMAL(20, 8)                          NOT NULL,
    close                        DECIMAL(20, 8)                          NOT NULL,
    volume                       DECIMAL(20, 8)                          NOT NULL,
    quote_asset_volume           DECIMAL(20, 8)                          NOT NULL,
    number_of_trades             BIGINT                                  NOT NULL,
    is_closed                    BOOLEAN                                 NOT NULL,
    taker_buy_base_asset_volume  DECIMAL(20, 8)                          NOT NULL,
    taker_buy_quote_asset_volume DECIMAL(20, 8)                          NOT NULL,
    CONSTRAINT pk_kline_data PRIMARY KEY (id)
);

CREATE TABLE user_balance
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   VARCHAR(255)                            NOT NULL,
    asset     VARCHAR(255)                            NOT NULL,
    free      DECIMAL                                 NOT NULL,
    locked    DECIMAL                                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_balance PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id      VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    active       BOOLEAN      NOT NULL,
    last_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE user_balance
    ADD CONSTRAINT uc_020b4cfc52f7cbb09ae939606 UNIQUE (user_id, asset, timestamp);

ALTER TABLE kline_data
    ADD CONSTRAINT uc_c2e0328a7f9e0a15176adb2f0 UNIQUE (symbol, open_time, interval);
