# Default configuration
spring:
  application:
    name: binance-connector

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5440/binance_connector
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: none # Use validate since we're using Flyway for migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  # Flyway configuration for automatic migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: binance-connector-group

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /api

# Binance API configuration
binance:
  api:
    key: ${BINANCE_API_KEY:}
    secret: ${BINANCE_API_SECRET:}
    symbols: BTCUSDT,ETHUSDT,BNBUSDT
    interval: 1m
    fetch-interval-seconds: 60
    fetch-user-data: true

# Kafka topics configuration
kafka:
  topics:
    kline-data: raw_kline_data
    user-balance: user_balance_data
    user-data: user_data

# Logging configuration
logging:
  level:
    com.acodexm.binanceconnector: INFO
    org.springframework: WARN
    org.hibernate: INFO
    org.flywaydb: INFO
