server:
  port: 8082

spring:
  application:
    name: data-loader-service
  datasource:
    url: jdbc:postgresql://localhost:5442/data_loader
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: data-loader-group

  flyway:
    clean-disabled: false # Be careful! This allows flyway:clean which drops all objects
    url: jdbc:postgresql://localhost:5442/data_loader
    user: postgres
    password: postgres

kafka:
  topics:
    user-balances: user_balance_data
    user-data: user_data
    time-market-data: time_market_data

timescale:
  enabled: true
  schema-init-timeout: 30s
