spring:
  datasource:
    url: jdbc:postgresql://timescaledb:5432/data_loader
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    com.acodexm.dataloader: INFO

portfolio:
  recalculation:
    interval: 300000  # 5 minutes in ms
