spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092

timescale:
  enabled: false  # Disable TimescaleDB for tests

portfolio:
  recalculation:
    interval: 10000  # 10 seconds for tests
